Raise FileNotFoundError if sql backend tries to read a file that does not exist
openpathsampling/openpathsampling pull request #1045
Opened 2021-08-03 16:15 UTC by sroet

I tried reading a file that did not exist in that directory, this lead to 2 things happening:
1) the file was created (this made it so that it took way to long before I figured out what was going on)
2) the code failed with: 
```
~/github_files/openpathsampling/openpathsampling/experimental/simstore/sql_backend.py in __init__(self, filename, mode, sql_dialect, **kwargs)
    148             )
    149             engine = sql.create_engine(self.connection_uri, **self.kwargs)
--> 150             self._initialize_from_engine(engine)
    151             self.mode = mode  # in case we changed when checking existence
    152 

~/github_files/openpathsampling/openpathsampling/experimental/simstore/sql_backend.py in _initialize_from_engine(self, engine)
    154         self.engine = engine
    155         self._metadata = sql.MetaData(bind=self.engine)
--> 156         self._initialize_with_mode(self.mode)
    157 
    158     @property

~/github_files/openpathsampling/openpathsampling/experimental/simstore/sql_backend.py in _initialize_with_mode(self, mode)
    208         elif mode == "r" or mode == "a":
    209             self.metadata.reflect(self.engine)
--> 210             self.schema = self.database_schema()
    211             self.table_to_number, self.number_to_table = \
    212                     self.internal_tables_from_db()

~/github_files/openpathsampling/openpathsampling/experimental/simstore/sql_backend.py in database_schema(self)
    592             schema dictionary
    593         """
--> 594         schema_table = self.metadata.tables['schema']
    595         sel = schema_table.select()
    596         with self.engine.connect() as conn:

KeyError: 'schema'
```
This PR ( in 7d90a63) adds logic to raise a FileNotFound error with a test

Implementing the code and running that test led to some Warning/Errors being raised, so I fixed those in the following commits:

293c867 resolves an error my coding enviroment was throwing about `self` not being defined in a `classmethod`
3d8f488 resolves a couple `DeprecationWarning: invalid escape sequence \(` (or `\.` )inside regex strings and resolves some pep8 complaints in touched files
b8d6947 resolves `SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)` in the proposed way ([documentation link](https://docs.sqlalchemy.org/en/14/core/reflection.html#fine-grained-reflection-with-inspector)) and removes a leftover `pytest.skip()` at the end of a completed test

2021-08-03 19:30 UTC, dwhswenson requested changes
Good catch! The fact that we have to do all this file handling ourselves frustrating, but it comes from the fact that most SQL databases don't really use a file model.

Tiny changes, mainly to use the SQLAlchemy as `sql` as in `sqlbackend.py`.

SQLAlchemy 1.4 made a bunch of changes. It's essentially a preview of their 2.0 while still maintaining some backward compatibility. There may be a number of other things we will have to change at some point, but they do have a [clear migration guide](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html). I think it's okay to require 1.4 even though it was just released in March, since I don't think we need to have backward compatibility for things in the experimental package.

2021-08-03 19:30 UTC, dwhswenson commented on openpathsampling/experimental/simstore/test_sql_backend.py
> +sqla = pytest.importorskip("sqlalchemy")
```suggestion
```

(or `import sqlalchemy as sql`)

1. `importorskip` shouldn't be necessary. If running SimStore tests, SQLAlchemy is a hard requirement. Ignoring these tests (unless you're running from the `experimental` directory) is handled by our `pytest.ini`.
2. You already have the import (as `sql`) from `from .sql_backend import *`. Actually, it looks like the more common short name for SQLAlchemy is `sa`, but lets stay consistent within the project.

(Some stats on "as" names [here](https://import-as.github.io/import/sqlalchemy.html), though I have no idea where the numbers come from. It seems to cover all short names with at most four characters. (No `paths`, but it does have [`toys`](https://import-as.github.io/import/openpathsampling.engines.toy.html) for the toy engine!)

2021-08-03 19:30 UTC, dwhswenson commented on openpathsampling/experimental/simstore/test_sql_backend.py
> +        table_names = sqla.inspect(database.engine).get_table_names()
```suggestion
        table_names = sql.inspect(database.engine).get_table_names()
```

2021-08-03 19:30 UTC, dwhswenson commented on openpathsampling/experimental/simstore/test_sql_backend.py
> +        table_names = sqla.inspect(self.database.engine).get_table_names()
```suggestion
        table_names = sql.inspect(self.database.engine).get_table_names()
```

2021-08-04 10:57 UTC, sroet commented
@dwhswenson added the suggestions, please have another look.

> Good catch! The fact that we have to do all this file handling ourselves frustrating, but it comes from the fact that most SQL databases don't really use a file model.

Yeah, I understand how from an sql perspective that they would just create a file if it does not exists. In this case we should deal with it to prevent users getting confused. I was mainly thrown for a loop when I did `ls` after getting the error and the file was actually there (it was just 0 bytes).

2021-08-04 15:54 UTC, dwhswenson approved these changes
LGTM! Merging.

Correcting my previous statement:

> since I don't think we need to have backward compatibility for things in the experimental package.

Should read: "I don't think we need to support old versions of requirements for things in the experimental package." I *do* think that at this point we need to support backward compatibility of files as much as possible. (Files made with today's version should open in tomorrow's version.)

2021-08-04 15:54 UTC, merged