WIP: Account for modifier acceptance in engine movers
openpathsampling/openpathsampling pull request #1075
Opened 2021-10-05 14:08 UTC by sroet

Closes #794 for all OPS classes
However, a new issue should be opened to discuss a refactor of `EngineMover` to take this and the other bias options [described in this comment]() into account for OPS 2.0.

Custom implementations of both `EngineMover` and `SnapshotModifier` should tyake care to implement this correctly on their end.

Big assumption (that might break API): **A key that starts with "bias" should not be present in `run_details` if it is not intended to be used for the bias calculation of a sample** 

todo:

- [ ] add functionality
- [ ]  add tests
- [ ]  update docstrings
- [ ]  make pep8 compliant
- [ ]  remove nose from touced tests (partial #756)

commit descriptions:
4f017dd adds probability_ratio to snapshot modifiers
ad7fad0 allows the usage of this probability ratio to be used as a bias in EngineMovers

2021-10-05 19:21 UTC, sroet commented
@dwhswenson This is ready for a review, all tests pass. 

Codecov issues are in code that was only altered to deal with pep8 (276e3b3). Do you have any tips on what kinds of tests should be added for that, or should I just revert the changes?

I would advice to have a look at the diff between abf0d99 and master and then the changes of 276e3b3 (should only be style, no altered code/functionality) and f591ca (only changes the tests)



Also, we should add an API 2.0 issue to at least align the init call of `AbstractTwoWayShootingMover` with `EngineMover` but preferably also refactor EngineMover to introduce the [proposed stages](https://github.com/openpathsampling/openpathsampling/issues/794#issuecomment-923830025) with their associated bias calculations

2021-10-05 22:32 UTC, dwhswenson reviewed
Before I go too much into detail, the main question is whether you're intending to follow this up with a the refactor for 2.0.

* **Implementation**: There are a couple of things I'd suggest changing in the implementation here, mainly to make a more complete refactor more straightforward. If you're going to have a PR for 2.0 coming soon, then we can deal most of those issues there (here, they'd require adding more compatibility code); if not, I'd rather make it easier to refactor later by getting the structure closer here. Specifically, issues are:

  1. Rather than taking the `bias*` namespace in details, I think it would make sense to directly call each of the `probability_ratio` methods in the same place. It's a little odd in the current setup that we need to look different places for the code that calculates different parts of the bias.
  2. If we're adding an implicit shooting point modifier for all engine movers, then I think should actually use it (even if it is often no modification, i.e., `new is old`), which would involve moving modification into the `EngineMover.__call__` method (just like shooting point selection).

  I'll go into more detail if needed, but those are the main issues.

* **Coverage**: It looks like most of this is related to stuff from `pathmover_inout.py`. Don't worry about it -- we can merge with failing patch coverage in this case. I'm personally in favor of completely removing `pathmover_inout.py` in OPS 2.0. It's untested and generally problematic. See discussion in [#557](https://github.com/openpathsampling/openpathsampling/pull/557).

2021-10-06 16:28 UTC, dwhswenson commented
More thoughts coming later, but here's a really quick one:

> even with NoModification I am pretty sure `new == old` but not `new is old` (only a copy is returned).

Looking at the code, you're correct. In usage here, I think we want the default modifier (for one-way shooting, e.g.) to return `new` such that `new is old`. My suggestion (pretty easy change to the current code):

```python
class NoModification(SnapshotModifier):
    def __init__(self, as_copy=True):
        # masking change to only certain atoms is nonsense for no modification
        super(NoModification, self).__init__(subset_mask=None)
        self.as_copy = as_copy

    def __call__(self, snapshot):
        return snapshot.copy() if self.as_copy else snapshot
```

Then use `NoModification(as_copy=False)` as the default in the changes here.

2021-10-09 19:17 UTC, dwhswenson requested changes
Pretty good. One typo and questions/suggestions about updating classes within our code rather than leaving them warning of deprecations.

2021-10-09 19:17 UTC, dwhswenson commented on openpathsampling/tests/test_spring_shooting.py
> +    def test_deprectation(self):
```suggestion
    def test_deprecation(self):
```

(spelling)

(And why test the deprecation instead of making to not issue the deprecation?)

2021-10-09 19:17 UTC, dwhswenson commented on openpathsampling/tests/test_shooting.py
> +                                                FinalFrameSelector])
Any reason not to just update these now (and make a quick subclass/instance of the base class if it isn't abstract) to test the deprecation call?

2021-10-18 11:34 UTC, dwhswenson commented on openpathsampling/tests/test_shooting.py
> +                                                FinalFrameSelector])
Got it. Thanks for the clarification!

2021-10-18 11:34 UTC, merged