Storage Handlers
openpathsampling/openpathsampling pull request #1158
Opened 2024-09-05 13:42 UTC by dwhswenson

These are intended to abstract out filesystem storage to be an arbitrary key-value store. As examples, I've implemented storage on the filesystem and in memory. Object storage (e.g., S3) can be implemented separately.

I'm making this a separate PR so that it can be used in future PRs.

I'd also appreciate suggestions on a better name! `StorageHandler` is kind of awful.

2024-09-05 14:25 UTC, dwhswenson commented
This is ready for review and comment. Without review, I will merge this after at least 24 hours, no sooner than Fri 06 Sep 15:00 GMT (17:00 my local).

2024-09-09 15:10 UTC, sroet requested changes
There are:
-  missing tests (mainly `__contains__` and `list_directory` calls)
- a typo
- Some unnecessary TemporaryDirectory magic
- Some missing docs on what `store` and `load` are intended to do (especially `load` behavior was unexpected)
- Strange layout of the base test class vs inheritance
- Some inconsistency if directories are handled or not

> I'd also appreciate suggestions on a better name! StorageHandler is kind of awful.

ChatGPT came up with (no strong preference from me):
> StorageManager
StorageHandler
AbstractStorage
StorageController
StorageService
DataStorageInterface
StorageProvider
StorageFacade
StorageGateway
StorageAbstraction

2024-09-09 15:10 UTC, sroet commented on openpathsampling/utils/storage_handlers.py
> +        os.remove(self.root / storage_label)
`self.transfer` can deal with directories, this does not, which functionality is intended?

2024-09-09 15:10 UTC, sroet commented on openpathsampling/utils/storage_handlers.py
> +        shutil.copyfile(local_path, target_path)
this could use docs, specifically of the difference between load and store (load seems to do something I would not expect from the name)

2024-09-09 15:10 UTC, sroet commented on openpathsampling/utils/storage_handlers.py
> +        return self._data[storage_label]
this could use docs, specifically on the difference between load and store

2024-09-09 15:10 UTC, sroet commented on openpathsampling/utils/storage_handlers.py
> +        os.remove(source_path)
this can't deal with directories

2024-11-10 03:09 UTC, dwhswenson reviewed
Thanks for the useful review! I made a few significant changes:

* Now nothing should work with directories. That's a little harder for wrapping an object store/key-value model, which is the goal here.
* Decided that I like `StorageInterface` more; changed some names
* Overall, better structure of ABCs with significantly better docs, although I count on inheritance when the subclasses have nothing to add to the doctoring.

Please take another look when you can!

2024-11-11 12:08 UTC, sroet approved these changes
One possible reuse of a variable, feel free to ignore.
LGTM otherwise

2024-11-14 23:06 UTC, merged