DOCS: Update AD TPS example, start move to nbsphinx
openpathsampling/openpathsampling pull request #937
Opened 2020-10-17 13:00 UTC by dwhswenson

This is a step toward refreshing and cleaning up the examples section of the docs, as well as moving to using nbsphinx instead of our internal `notebook` directive.

- [x] Use nbsphinx for AD TPS and toy MSTIS examples
- [x] Put more emphasis on the [tutorial](https://gitlab.e-cam2020.eu/dwhswenson/ops_tutorial) as a place to start
- [x] Fix the problem with for the step visualizer showing multiple plots in output cells during equilibration in the AD TPS example
- [x] Use `VisitAllStatesEnsemble` to get high-temperature trajectory; move discussion of how that works to a separate document.
- [x] Update AD TPS notebooks for more modern usage (parts hadn't been updated since May 2016!!)

When @jhprinz wrote our `notebook` directive, [nbsphinx](https://github.com/spatialaudio/nbsphinx) didn't exist. Now it is a mature and well-maintained project. I'd rather use something that someone else maintains, instead of having to worry about maintaining our own code for it. Plus, I think it renders a little better (and I'm not interested in tweaking our CSS until it looks as good).

As we move to nbsphinx, this means that instead of having all notebooks for a multi-part example on one web page, they will each be on their own page. There may be a way to avoid that, but I actually think it is better, anyway.

I've only moved to nbsphinx for the highlighted examples, just in case people absolutely hate this approach.

2020-10-17 13:15 UTC, dwhswenson commented
This is ready for review and comment. I will leave it open for at least 24 hours, merging no earlier than Sun 18 Oct 16:00 local (14:00 GMT).

2020-10-17 14:56 UTC, sroet requested changes
Main feedback:
all the fixed-lenght notebooks should get some love and use `python 3` `print` functions.

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_1b_trajectory.ipynb
> +  },
I can't comment on line `14`, but that should be changed from
```
"This notebook is part of the fixed length TPS example. It requires the file `alanine_dipeptide_tps_equil.nc`, which is written in the notebook `alanine_dipeptide_tps_first_traj.ipynb`.\n"
```
to
```
"This notebook is part of the fixed length TPS example. It requires the file `ad_tps_equil.nc`, which is written in the notebook `AD_tps_1_trajectory.ipynb`.\n"
```
Also line `30` should add
```
from __future__ import print_function
```

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_1b_trajectory.ipynb
> +   "metadata": {},
Can't comment on line `39` or line `50` but those should be changed from:
```
"First, we open the file we made in `alanine_dipeptide_tps_first_traj.ipynb` and load various things we need from that."
```
to 
```
"First, we open the file we made in `AD_tps_1_trajectory.ipynb` and load various things we need from that."
```
and from
```
"old_storage = paths.Storage(\"tps_nc_files/alanine_dipeptide_tps_equil.nc\", \"r\")"
```
to
```
"old_storage = paths.Storage(\"ad_tps_equil.nc\", \"r\")"
```

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_1b_trajectory.ipynb
> +   "metadata": {},
Line `112` should use 
`print(trajectories)` 
instead of
`print trajectories`

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_1b_trajectory.ipynb
> +   "metadata": {},
line `131` should go from
```
"This is exactly as done in `alanine_dipeptide_tps_first_traj.ipynb`."
```
to 
```
"This is exactly as done in `AD_tps_1_trajectory.ipynb`."

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_1b_trajectory.ipynb
> +   "metadata": {},
line `196` should not have the `tps_nc_files` trajectory

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_1b_trajectory.ipynb
> +   "metadata": {},
Before line `219` a template `trajectory`/`snapshot` has to be saved (otherwise it errors out)

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_2b_run_fixed.ipynb
> +  },
line `14` should change 
`alanine_dipeptide_fixed_tps_traj.ipynb`
to
`AD_tps_1b_trajectory.ipynb`

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_2b_run_fixed.ipynb
>      "old_storage = paths.Storage(\"tps_nc_files/alanine_dipeptide_fixed_tps_traj.nc\", \"r\")"
this line should be in line with the final name used in `AD_tps_1b_trajectory` (with or without the directory, whatever you decide)

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_2b_run_fixed.ipynb
> +  },
The first code cell should also have

```
from __future__ import print_function
```

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_2b_run_fixed.ipynb
> +   "metadata": {},
The `print` statements should be functions

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_2b_run_fixed.ipynb
>      "sampler = paths.PathSampling(storage=paths.Storage(\"tps_nc_files/alanine_dipeptide_fixed_tps.nc\", \"w\", template),\n",
This filename should probably don't include the directory to keep inline with the other notebooks
```suggestion
    "sampler = paths.PathSampling(storage=paths.Storage(\"alanine_dipeptide_fixed_tps.nc\", \"w\", template),\n",
```

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_2b_run_fixed.ipynb
> +   "metadata": {},
on line `177` 
```
alanine_dipeptide_tps_analysis.ipynb
```
should be changed to 
```
AD_tps_3b_analysis_fixed.ipynb
```

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_3b_analysis_fixed.ipynb
>      "logging.config.fileConfig(\"timed_logging.conf\", disable_existing_loggers=False)"
This line fails

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_3b_analysis_fixed.ipynb
> +  },
The print statements should be made into functions throughout this notebook

2020-10-17 14:56 UTC, sroet commented on examples/alanine_dipeptide_tps/AD_tps_4_advanced.ipynb
> +  },
This notebook should be updated to use the new storage filenames, `print` should be functions

2020-10-23 04:21 UTC, dwhswenson commented
Reran the fixed length AD TPS (some of that took a long time). Updated it for modern OPS and ran it in Python 3. Note that this PR now includes #938, so will be merged after that.

2020-10-23 16:14 UTC, dwhswenson commented
pinging @sroet to see if this fixed everything: it should, since it now runs on Python 3!

2020-10-23 16:46 UTC, sroet commented
It runs!
I did have some comments about the markdown in `AD_tps_2b_run_fixed.ipynb`:
- second markdown cell still uses old names for the `.nc` and `.ipynb` 
- TPS markdown cell still uses the old name for the flexible `.ipynb` 
- last markdown cell still references the old analysis `.ipynb`

Those were the only comments I had left

2020-10-23 16:56 UTC, dwhswenson commented
Thanks! Fixed those. Will leave this up for another hour or so just in case there's anything else, but I'm eager to get this merged in. In particular, this PR does a much better job of emphasizing the separate tutorial repo, which is my first recommendation for where to start.

The one downside I've noticed about the nbsphinx-generated docs is that our path trees lose the nice highlight-on-hover effect. At some point, it would be worth trying to get that back, perhaps with custom CSS (unless they're converting our SVGs to something else).

2020-10-23 17:06 UTC, sroet commented
> Will leave this up for another hour or so just in case there's anything else,

Those were the ones I spotted, so you don't have to wait for me!

2020-10-24 04:24 UTC, merged